name: Main workflow

on:
  workflow_dispatch:
    inputs:
      check:
        required: true
        type: boolean

jobs:
  check:
    uses: NiranjanOrgGround/reusable-workflow/.github/workflows/reusable.yml@main
    with:
      check: inputs.check
