name: Main workflow

on:
  workflow_dispatch:
    inputs:
      check:
        required: true
        type: boolean

jobs:
  print-check:
    runs-on: ubuntu-latest
    steps:
      - name: Print Check Input
        run: echo "Raw Check input value: '${{ inputs.check }}'"
